version: '3.8'
services:
  frontend:
    build: ./react-installed
    container_name: react-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./react-installed:/app
      - /app/node_modules